# Generated by Django 5.2.14 on 2026-06-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "연차"),
                            ("PUBLIC", "공가"),
                            ("SICK", "병가"),
                            ("MORNING_HALF", "오전반차"),
                            ("AFTERNOON_HALF", "오후반차"),
                        ],
                        max_length=20,
                        verbose_name="휴가종류",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="일수"
                    ),
                ),
                (
                    "doc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_request",
                        to="approvals.approvaldoc",
                    ),
                ),
            ],
            options={
                "verbose_name": "휴가신청",
                "verbose_name_plural": "휴가신청 목록",
            },
        ),
    ]
