# Generated by Django 5.2.14 on 2026-06-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_request",
                        to="approvals.approvaldoc",
                    ),
                ),
                (
                    "expense_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_expense_source",
                        to="approvals.approvaldoc",
                        verbose_name="지출결의서",
                    ),
                ),
            ],
            options={
                "verbose_name": "구매요청",
                "verbose_name_plural": "구매요청 목록",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="품명")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="단가"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="수량")),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchaserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "구매항목",
            },
        ),
    ]
