# Generated by Django 5.2.14 on 2026-06-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="목적지"),
                ),
                ("start_date", models.DateField(verbose_name="출발일")),
                ("end_date", models.DateField(verbose_name="귀환일")),
                ("purpose", models.TextField(verbose_name="출장목적")),
                (
                    "doc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_request",
                        to="approvals.approvaldoc",
                    ),
                ),
                (
                    "expense_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_expense_source",
                        to="approvals.approvaldoc",
                        verbose_name="지출결의서",
                    ),
                ),
            ],
            options={
                "verbose_name": "출장신청",
                "verbose_name_plural": "출장신청 목록",
            },
        ),
    ]
