# Generated by Django 5.2.14 on 2026-06-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "check_in",
                    models.TimeField(blank=True, null=True, verbose_name="출근시간"),
                ),
                (
                    "check_out",
                    models.TimeField(blank=True, null=True, verbose_name="퇴근시간"),
                ),
                (
                    "is_business_trip",
                    models.BooleanField(default=False, verbose_name="출장여부"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="비고"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="직원",
                    ),
                ),
            ],
            options={
                "verbose_name": "근태기록",
                "verbose_name_plural": "근태기록 목록",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
